[package]
name = "candle-cudnn-attn"
description = "cuDNN attention bindings for candle"
homepage = "https://github.com/huggingface/candle-extensions/candle-cudnn-attn/"
documentation = "https://docs.rs/candle-cudnn-attn"
readme = "README.md"
version.workspace = true
edition.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
candle = { workspace = true }
cudarc = { workspace = true }
thiserror = "1.0"
libc = "0.2"

[build-dependencies]
bindgen = "0.69"

[features]
default = []
cuda = []